### ISSUE TITLE
Can not run in windows 10

### ISSUE THREAD

**Issue by vsboost** [avk-sw/pocsag2sdr#2]
Hi there, previous version 0.1 worked well in Windows10, new one throws up error.
![image](https://cloud.githubusercontent.com/assets/11001973/14939082/b8be2e42-0f7b-11e6-9b2a-ecf4d37ad7db.png)

**Comment by avk-sw** [comment]
Hi vsboost,

Thank you for reporting the issue.
pocsag2sdr.exe available at https://github.com/avk-sw/pocsag2sdr/tree/master/bin is 32 bit application compiled with XP tool chain for wider compatibilty.
If it was 16 bit application, then I wouldn't be able to run it on my Windows 7 x64 either as it doesn't support 16 bit applications as well.
Unfortunately, I haven't tested pocsag2sdr.exe with Windows 10, and your issue is a good reason for that. It'll take some time as I don't have Win10 at hand.

**Comment by vsboost** [comment]
Thanks avk-sw, ill stick with v0.1 for now as it works no problem with Win10.

Thanks again

**Comment by vsboost** [comment]
Im closing this as i realised that right clicking on the exe file and saving as on github messes things up, i downloaded the zip of master and extracted the exe it runs fine, sorry for the confusion.

**Comment by avk-sw** [comment]
No problem, and thank you for the info about percularities of file downloading from GitHub!
